config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'notes#index'
  resources :notes, except: %i[new update edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :notes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :fullname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :find_note!, only: [:destroy]
  ITEMS_PER_PAGE = 5

  def index
    @pagy, @notes = pagy(Note.includes(:user).order(created_at: :asc), items: ITEMS_PER_PAGE, size: [1, 1, 1, 1])
  rescue Pagy::OverflowError => e
    redirect_to root_path(page: e.pagy.last)
  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to root_path(page: current_page), notice: 'Note created successfully.'
    else
      redirect_to root_path(page: current_page), alert: 'Failed to create note.'
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path(page: current_page), notice: 'Note deleted successfully.'
  end

  private

  def current_page
    match = request.headers['HTTP_REFERER']&.match(/page=(\d+)/)
    return 1 if match.nil?

    match[1]
  end

  def find_note!
    @note = Note.find_by!(user: current_user, id: params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Note not found'
  end

  def note_params
    params.require(:note).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :fullname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :fullname, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def authored_by_current_user?(note)
    note.user == current_user
  end

  def formatted_date(date)
    date.strftime('%Y-%m-%d')
  end

  def formatted_time(date)
    date.strftime('%H:%M:%S')
  end

  def formatted_note_count(count)
    pluralize(count, 'note')
  end
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light" style="min-width: 300px;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link text-primary"><%= current_user.fullname %></span>
          </li>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path,
              data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-small btn-primary mx-2" %>
          </li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notekeeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <div class="container-fluid"
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<tr>
  <td></td>
  <td colspan="3">
    <%= form_with model: Note.new, url: notes_path,
                  data: { controller: 'note-form', 'note-form-target': 'form' } do |form| %>
      <%= form.text_field :content, class: "form-control", placeholder: "WRITE A NEW NOTE", required: true,
                          data: { action: 'change->note-form#submit keydown->note-form#preventEnterSubmit' }%>
    <% end %>
  </td>
  <td></td>
</tr>

app/views/notes/_note.html.erb
<tr>
  <td><%= line_number %></td>
  <td><%= note.content %></td>
  <td data-bs-toggle="tooltip" data-bs-placement="top" title="<%= note.user.fullname %>">
    <%= note.user.name %>
  </td>
  <td data-bs-toggle="tooltip" data-bs-placement="top" title="<%= formatted_time(note.created_at) %>">
    <%= formatted_date(note.created_at) %>
  </td>
  <td>
    <% if authored_by_current_user?(note) %>
      <%= link_to note_path(note), class: "delete-note",
                  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
        <i class="bi bi-trash"></i>
      <% end %>
    <% else %>
      <i class="bi bi-x-circle text-decoration-line-through" data-bs-toggle="tooltip" data-bs-placement="top"
         title="You can delete only your own note"></i>
    <% end %>
  </td>
</tr>

app/views/notes/index.html.erb
<div class="container" >
  <div class="row">
    <div class="col" style="max-width: 640px;">
      <h1 class="text-center-sm text-right-lg mt-4 mb-4"> <%= formatted_note_count(@pagy.count) %> </h1>
    </div>
  </div>
  <div class="row" data-controller="tooltip">
    <div class="col">
      <div class="table-responsive" style="min-width: 300px; max-width: 640px;">
        <table class="table">
          <thead>
          <tr>
            <th style="width: 20px">#</th>
            <th>Note text</th>
            <th style="width: 80px">Author name</th>
            <th style="width: 120px">Create date</th>
            <th style="width: 20px"></th>
          </tr>
          </thead>
          <tbody>
            <% @notes.each.with_index(@pagy.offset + 1) do |note, line_number| %>
              <%= render 'note', { note: note, line_number: line_number } %>
            <% end %>

            <% if user_signed_in? %>
              <%= render 'form' %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>